[package]
name = 'rfqtk'
version = '0.1.0'
edition = '2021'
rust-version = '1.65'
publish = false

[lib]
name = 'rfqtk'
crate-type = [ 'staticlib' ]
path = "src/lib.rs"  

[dependencies]
extendr-api = "0.8.1"          
fqtk = "0.3.1"

[profile.release]
panic = "unwind"