[package]
name = 'rfqtk'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.65'

[lib]
crate-type = [ 'staticlib' ]
name = 'rfqtk'
path = "src/lib.rs"  

[dependencies]
extendr-api = "0.8.0"          
fqtk = "0.3.1"
